---
title: 'Predictive Modeling : Credit Default Prediction based on who a creditos friends
  are'
output: html_document
---



```{r}
library(igraph)
#--------------------------------------
# get data 
#--------------------------------------
 
# specify the adjacency matrix
M <- matrix(c(0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0, 0, 0, 1, 0, 0, 0, 0, 0, 0,1, 1, 1, 0, 1, 0, 0, 0, 1, 0,0,0, 0, 1, 0, 1, 1, 1, 0, 0,0, 0, 0, 0, 1, 0, 0, 0, 0, 0,0 ,0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,0,0, 0, 1, 0, 0, 0, 0, 0, 1,0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ),10,10, byrow= TRUE)
M

G<-graph.adjacency(M, mode=c("undirected"))               # convert key player network matrix to an igraph object    
betweenness(G)
evcent(G)
evcent(G)$vector
cent<-data.frame(bet=betweenness(G),eig=evcent(G)$vector) # calculate betweeness & eigenvector centrality 

# Calculate how the betweenness and the eigenvector centrality are related - using linear regression function
lm(eig~bet,data=cent)

# calculate what are the residuals for all of the ten data i.e by how much does the calculate deviate from the actual result when the formulaer is applied to the ten instances of data
lm(eig~bet,data=cent)$residuals

res<-as.vector(lm(eig~bet,data=cent)$residuals)           # calculate residuals
res
cent
# Add the column res to its respective 10 data  instances
cent<-transform(cent,res=res)                             # add to centrality data set
cent

write.csv(cent,"r_keyactorcentrality.csv")                  # save in project folder
 
#--------------------------------------
# visualize the network
#--------------------------------------
 
# plot that reflects correct vertex names and scaled by centrality

plot(G, layout = layout.fruchterman.reingold, vertex.size = 20*evcent(G)$vector, vertex.label = as.vector(rownames(cent)))
 
#-------------------------------------------
# create Credit Risk analysis  now
#------------------------------------------
 
id <- c(1,2,3,4,5,6,7,8,9,10)  # create individual id's for reference
income <- c(35000, 37000, 43000, 63000, 72000, 27000, 30000, 34000, 45000, 55000) # income
default <- c(1,1,1,0,0,1,1,1,1,1) # default indicator
 
#-------------------------------------------
# basic regression
#------------------------------------------
cent
# add the betweenness and the eigen vecotr centrality and the residual as the paarameter to the dataset, then we will 
# perform the liner regression on the data and see how does the eigenvector and centrality affect the default
# i.e Analyse  how the peoples default on load behaviour changes depending on how  connected they are and how well connected to  the influentioal person they are. 
# Compare with the previous linear regression if the coeficient value of th income changes significantly when the two params are considered. If yes, then it imple that it likely implies that the cconnected  affect the connectedness.
# If the betweenness adn centrality has no role the it should have lest coeficient value . 
# Alos we should check for correlation between the betweenness and the other prominent factors. If there is high correlation betweene the income and the connectedness then it likely implies that both mean almost similar thing and that the they are possible mis represented by being duplicated.
# that is why we try to avoid the params with high correlation.
creditrisk <- cbind(id,income, cent, default) # combine with eigenvector centrality derived above
creditrisk

# model default risk as a function of income and network relationship  
lm(creditrisk$default ~  creditrisk$eig + creditrisk$income) 
lm(creditrisk$default ~  creditrisk$income) 
lm(creditrisk$default ~  creditrisk$eig)
lm(creditrisk$default ~  creditrisk$bet)

# The higher the betweeenness value lower is the  default probability i.e the higher  a person lies in along the short path, the lesser likely is he to default. Since defaulting will probably increase the chance of him creating the social reputation. severing the reputation mens severing the links between people.

# Eigenvector has more impact, i.e the more well connected the people are, the lesser is the chance of default i.e 


# OLS
model1 <- lm(creditrisk$default ~  creditrisk$eig + creditrisk$income) 
summary(model1)


```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
